# Generated by Django 2.2.3 on 2020-02-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='callback',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='callback_default',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='company',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='services',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='state',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='visa_status',
        ),
        migrations.AddField(
            model_name='signup',
            name='utc_callback',
            field=models.DateTimeField(null=True),
        ),
    ]
